# Generated by Django 4.1.4 on 2023-01-07 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Home",
            fields=[
                (
                    "home_id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=255)),
                ("postnummer", models.PositiveIntegerField()),
                ("type", models.CharField(max_length=255)),
                ("by", models.CharField(max_length=255)),
                ("kommune", models.CharField(max_length=255)),
                ("region", models.CharField(max_length=255)),
                ("energi", models.CharField(max_length=255)),
                ("liggetid", models.PositiveIntegerField()),
                ("areal", models.PositiveIntegerField()),
                ("grund", models.PositiveIntegerField()),
                ("year_built", models.PositiveIntegerField()),
                ("year_renovated", models.PositiveIntegerField()),
                ("pris", models.PositiveIntegerField()),
                ("rum", models.PositiveIntegerField()),
                ("toiletter", models.PositiveIntegerField()),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Score",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "home",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scores",
                        to="spil.home",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scores",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.CharField(max_length=1000)),
                ("caption", models.CharField(blank=True, max_length=255)),
                (
                    "home",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="spil.home",
                    ),
                ),
            ],
        ),
    ]
