# Generated by Django 4.1.4 on 2023-02-26 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spil", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="score",
            name="bidinterest",
            field=models.CharField(
                choices=[("Nej", "Nej"), ("Ja", "Ja")],
                default="Nej",
                max_length=3,
                verbose_name="Ville du byde på denne bolig?",
            ),
        ),
        migrations.AddField(
            model_name="score",
            name="priceguess",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Hvad tror du boligens udbudspris er?"
            ),
        ),
        migrations.AlterField(
            model_name="score",
            name="score",
            field=models.PositiveIntegerField(
                choices=[(1, "1 min"), (2, "2"), (3, "3"), (4, "4"), (5, "5 max")],
                default=3,
                verbose_name="Hvad er din vurdering af boligen?",
            ),
        ),
    ]
