# Generated by Django 4.1.4 on 2023-04-02 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spil", "0002_score_bidinterest_score_priceguess_alter_score_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="home",
            name="latitude",
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name="home",
            name="longitude",
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20),
        ),
    ]
