# Generated by Django 4.1.4 on 2023-05-06 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spil", "0003_home_latitude_home_longitude"),
    ]

    operations = [
        migrations.AlterField(
            model_name="home",
            name="areal",
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20),
        ),
    ]
