# Generated by Django 4.1.4 on 2023-05-06 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spil", "0004_alter_home_areal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="home",
            name="grund",
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name="home",
            name="pris",
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name="home",
            name="rum",
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name="home",
            name="toiletter",
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name="home",
            name="year_built",
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name="home",
            name="year_renovated",
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20),
        ),
    ]
