# Generated by Django 4.1.4 on 2023-05-06 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spil", "0005_alter_home_grund_alter_home_pris_alter_home_rum_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="home",
            name="home_id",
            field=models.CharField(max_length=2000, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="score",
            name="priceguess",
            field=models.DecimalField(
                decimal_places=10,
                default=0,
                max_digits=20,
                verbose_name="Hvad tror du boligens udbudspris er?",
            ),
        ),
    ]
