# Generated by Django 4.1.4 on 2023-05-06 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spil", "0007_alter_score_priceguess"),
    ]

    operations = [
        migrations.AlterField(
            model_name="home",
            name="areal",
            field=models.DecimalField(decimal_places=1, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name="home",
            name="grund",
            field=models.DecimalField(decimal_places=1, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name="home",
            name="pris",
            field=models.DecimalField(decimal_places=1, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name="home",
            name="rum",
            field=models.DecimalField(decimal_places=1, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name="home",
            name="toiletter",
            field=models.DecimalField(decimal_places=1, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name="home",
            name="year_built",
            field=models.DecimalField(decimal_places=1, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name="home",
            name="year_renovated",
            field=models.DecimalField(decimal_places=1, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name="score",
            name="priceguess",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                max_digits=20,
                verbose_name="Hvad tror du boligens udbudspris er?",
            ),
        ),
    ]
